name: Run iOS Tests

on:
  workflow_call:
  workflow_dispatch:

jobs:
  ios-tests:
    runs-on: macos-15-xlarge

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Install example dependencies
      working-directory: example
      run: npm install

    - name: Prebuild iOS project
      working-directory: example
      run: npm run prebuild:ios

    - name: Use Xcode 16.4
      run: sudo xcode-select -switch /Applications/Xcode_16.4.app

    - name: Build app for testing
      working-directory: example/ios
      run: |
        xcodebuild build-for-testing \
          -workspace expoemarsyspluginexample.xcworkspace \
          -scheme expoemarsyspluginexample \
          -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.6' \
          -quiet

    - name: Run iOS Tests
      working-directory: example/ios
      run: |
        xcodebuild test \
          -workspace expoemarsyspluginexample.xcworkspace \
          -scheme ExpoPluginForSAPEmarsysTest \
          -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.6'
